spring:

  application:
    name: java_education

  output:
    ansi:
      enabled: always

  profiles:
    active: dev

  # Database connection
  datasource:
    url: jdbc:mysql://localhost:3306/education
    username: user
    password: pass
  driver:
    class: name:com.mysql.cj.jdbc.Driver # database connection driver
  jpa:
    hibernate:
      ddl-auto: update # create tables automatically
    open-in-view: false

var1: "contenido de var1"
var2: 100

